FROM python:3.12

WORKDIR /app
# RUN apt-get update && apt-get install -y build-essential libffi-dev libyaml-dev

# 配置pip使用国内镜像源
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip config set global.trusted-host pypi.tuna.tsinghua.edu.cn
RUN pip config set global.timeout 300

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --timeout=300 --retries=3 -r requirements.txt

COPY ./app /app


CMD ["fastapi","run","app/main.py","--host","0.0.0.0","--port","8000"]