"""添加数据字典

Revision ID: 001da528b756
Revises: 
Create Date: 2022-11-08 10:11:55.957440

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '001da528b756'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_dict',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, comment='字典名称'),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False, comment='字典编号'),
    sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True, comment='描述'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dict_item',
    sa.Column('enable', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, comment='名称'),
    sa.Column('data', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False, comment='数据值'),
    sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True, comment='描述'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序值，越小越靠前'),
    sa.Column('dict_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dict_id'], ['data_dict.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dict_item')
    op.drop_table('data_dict')
    # ### end Alembic commands ###
