"""菜单添加icon图标字段

Revision ID: 02cae67f3be4
Revises: b703662d9cf9
Create Date: 2022-11-02 13:54:41.361623

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02cae67f3be4'
down_revision = 'b703662d9cf9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, comment='Icon图标'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'icon')
    # ### end Alembic commands ###
