"""primary default None

Revision ID: 0ac6e1ad94c1
Revises: af054468f986
Create Date: 2021-12-08 10:36:44.892537

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision = '0ac6e1ad94c1'
down_revision = 'af054468f986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
