"""init db

Revision ID: 11b84a0bbb8d
Revises: 
Create Date: 2021-09-24 20:56:32.811434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11b84a0bbb8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_menu')
    op.drop_table('menu')
    op.add_column('roles', sa.Column('role', sa.String(), nullable=True))
    op.add_column('roles', sa.Column('disable', sa.Boolean(), nullable=True))
    op.drop_index('role_unique', table_name='roles')
    op.create_unique_constraint(None, 'roles', ['role'])
    op.drop_column('roles', 'enable')
    op.drop_column('roles', 'description')
    op.drop_column('roles', 'name')
    op.add_column('user_roles', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('user_roles', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='对应user表中的id')
    op.alter_column('user_roles', 'role_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='对应role表中的id',
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment=None,
               existing_comment='用户名',
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='密码',
               existing_nullable=True)
    op.alter_column('users', 'enable',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='1：启用，0：禁用',
               existing_nullable=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'email')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True))
    op.add_column('users', sa.Column('email', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'enable',
               existing_type=mysql.TINYINT(display_width=1),
               comment='1：启用，0：禁用',
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment='密码',
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment='用户名',
               existing_nullable=True)
    op.alter_column('user_roles', 'role_id',
               existing_type=mysql.INTEGER(),
               comment='对应role表中的id',
               existing_nullable=True)
    op.alter_column('user_roles', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='对应user表中的id')
    op.drop_column('user_roles', 'id')
    op.add_column('roles', sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255), nullable=True, comment='角色名'))
    op.add_column('roles', sa.Column('description', mysql.VARCHAR(collation='utf8mb4_general_ci', length=128), nullable=True))
    op.add_column('roles', sa.Column('enable', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='1启用，0禁用'))
    op.drop_constraint(None, 'roles', type_='unique')
    op.create_index('role_unique', 'roles', ['name'], unique=False)
    op.drop_column('roles', 'disable')
    op.drop_column('roles', 'role')
    op.create_table('menu',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=128), nullable=True, comment='菜单名'),
    sa.Column('path', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('component', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('role_menu',
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('menu_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
