"""添加菜单排序字段

Revision ID: a5e2cea226d4
Revises: 334040db4d77
Create Date: 2022-10-31 09:44:30.289049

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5e2cea226d4'
down_revision = '334040db4d77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('sort', sa.Integer(), nullable=True, comment='菜单排序'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'sort')
    # ### end Alembic commands ###
