"""init

Revision ID: af054468f986
Revises: 
Create Date: 2021-12-08 10:05:08.390749

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel 
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af054468f986'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='1：是，删除，0：否，未删除',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.create_index(op.f('ix_assets_area'), 'assets', ['area'], unique=False)
    op.create_index(op.f('ix_assets_category'), 'assets', ['category'], unique=False)
    op.create_index(op.f('ix_assets_deleted'), 'assets', ['deleted'], unique=False)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_manager'), 'assets', ['manager'], unique=False)
    op.create_index(op.f('ix_assets_user'), 'assets', ['user'], unique=False)
    op.drop_constraint('assets_ibfk_1', 'assets', type_='foreignkey')
    op.alter_column('category', 'name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='资产类别名（英文）',
               existing_nullable=True)
    op.alter_column('category', 'alias',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='资产类别别名（中文）',
               existing_nullable=True)
    op.alter_column('category', 'desc',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='描述',
               existing_nullable=True)
    op.create_index(op.f('ix_category_alias'), 'category', ['alias'], unique=False)
    op.create_index(op.f('ix_category_desc'), 'category', ['desc'], unique=False)
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.alter_column('category_field', 'name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50),
               comment=None,
               existing_comment='字段',
               existing_nullable=True)
    op.alter_column('category_field', 'desc',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='字段描述',
               existing_nullable=True)
    op.alter_column('category_field', 'type',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='字段类型：字符串text，整数number，日期时间date或datetime',
               existing_nullable=True)
    op.alter_column('category_field', 'need',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='必须，0否，1是',
               existing_nullable=True)
    op.alter_column('category_field', 'multi',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='多值，0否，1是',
               existing_nullable=True)
    op.alter_column('category_field', 'show',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否在资产页面显示字段，0：否，1：显示',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('category_field', 'category_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='category表的外键',
               existing_nullable=True)
    op.create_index(op.f('ix_category_field_category_id'), 'category_field', ['category_id'], unique=False)
    op.create_index(op.f('ix_category_field_desc'), 'category_field', ['desc'], unique=False)
    op.create_index(op.f('ix_category_field_id'), 'category_field', ['id'], unique=False)
    op.create_index(op.f('ix_category_field_multi'), 'category_field', ['multi'], unique=False)
    op.create_index(op.f('ix_category_field_name'), 'category_field', ['name'], unique=False)
    op.create_index(op.f('ix_category_field_need'), 'category_field', ['need'], unique=False)
    op.create_index(op.f('ix_category_field_show'), 'category_field', ['show'], unique=False)
    op.create_index(op.f('ix_category_field_type'), 'category_field', ['type'], unique=False)
    op.alter_column('menu', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               comment=None,
               existing_comment='菜单名',
               existing_nullable=True)
    op.alter_column('menu', 'type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               nullable=True,
               comment=None,
               existing_comment='page or button')
    op.alter_column('menu', 'enable',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment=None,
               existing_comment='菜单状态，1可用，0不可用',
               existing_server_default=sa.text("'1'"))
    op.alter_column('menu', 'url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='后端权限判断用的',
               existing_nullable=True)
    op.create_index(op.f('ix_menu_component'), 'menu', ['component'], unique=False)
    op.create_index(op.f('ix_menu_enable'), 'menu', ['enable'], unique=False)
    op.create_index(op.f('ix_menu_id'), 'menu', ['id'], unique=False)
    op.create_index(op.f('ix_menu_name'), 'menu', ['name'], unique=False)
    op.create_index(op.f('ix_menu_parent_id'), 'menu', ['parent_id'], unique=False)
    op.create_index(op.f('ix_menu_path'), 'menu', ['path'], unique=False)
    op.create_index(op.f('ix_menu_type'), 'menu', ['type'], unique=False)
    op.create_index(op.f('ix_menu_url'), 'menu', ['url'], unique=False)
    op.create_index(op.f('ix_role_category_category_id'), 'role_category', ['category_id'], unique=False)
    op.create_index(op.f('ix_role_category_role_id'), 'role_category', ['role_id'], unique=False)
    op.create_foreign_key(None, 'role_category', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'role_category', 'category', ['category_id'], ['id'])
    op.drop_index('role_menu_unique', table_name='role_menu')
    op.create_index(op.f('ix_role_menu_menu_id'), 'role_menu', ['menu_id'], unique=False)
    op.create_index(op.f('ix_role_menu_role_id'), 'role_menu', ['role_id'], unique=False)
    op.create_foreign_key(None, 'role_menu', 'menu', ['menu_id'], ['id'])
    op.create_foreign_key(None, 'role_menu', 'roles', ['role_id'], ['id'])
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               nullable=False,
               comment=None,
               existing_comment='角色名')
    op.alter_column('roles', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               nullable=False)
    op.alter_column('roles', 'enable',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment=None,
               existing_comment='1启用，0禁用',
               existing_server_default=sa.text("'1'"))
    op.drop_index('role_unique', table_name='roles')
    op.create_index(op.f('ix_roles_description'), 'roles', ['description'], unique=False)
    op.create_index(op.f('ix_roles_enable'), 'roles', ['enable'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.alter_column('system', 'info',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='其他信息',
               existing_nullable=True)
    op.alter_column('system', 'host',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=125),
               comment=None,
               existing_comment='主机名',
               existing_nullable=True)
    op.alter_column('system', 'ip',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment=None,
               existing_comment='IP地址',
               existing_nullable=True)
    op.alter_column('system', 'system',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='操作系统',
               existing_nullable=True)
    op.alter_column('system', 'storage',
               existing_type=mysql.BIGINT(),
               nullable=True,
               comment=None,
               existing_comment='硬盘空间，单位G')
    op.alter_column('system', 'memory',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='内存空间，单位G',
               existing_nullable=True)
    op.alter_column('system', 'cpu',
               existing_type=mysql.TINYINT(),
               comment=None,
               existing_comment='CPU数量',
               existing_nullable=True)
    op.alter_column('system', 'admin',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='运维人员名字',
               existing_nullable=True)
    op.alter_column('system', 'env',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='正式、测试环境',
               existing_nullable=True)
    op.alter_column('system', 'type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='物理机、虚拟机',
               existing_nullable=True)
    op.alter_column('system', 'project',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='项目名称',
               existing_nullable=True)
    op.alter_column('system', 'developer',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='三线开发人员',
               existing_nullable=True)
    op.create_index(op.f('ix_system_admin'), 'system', ['admin'], unique=False)
    op.create_index(op.f('ix_system_cpu'), 'system', ['cpu'], unique=False)
    op.create_index(op.f('ix_system_developer'), 'system', ['developer'], unique=False)
    op.create_index(op.f('ix_system_env'), 'system', ['env'], unique=False)
    op.create_index(op.f('ix_system_host'), 'system', ['host'], unique=False)
    op.create_index(op.f('ix_system_id'), 'system', ['id'], unique=False)
    op.create_index(op.f('ix_system_ip'), 'system', ['ip'], unique=False)
    op.create_index(op.f('ix_system_memory'), 'system', ['memory'], unique=False)
    op.create_index(op.f('ix_system_project'), 'system', ['project'], unique=False)
    op.create_index(op.f('ix_system_storage'), 'system', ['storage'], unique=False)
    op.create_index(op.f('ix_system_system'), 'system', ['system'], unique=False)
    op.create_index(op.f('ix_system_type'), 'system', ['type'], unique=False)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment=None,
               existing_comment='用户名',
               existing_nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='密码',
               existing_nullable=True)
    op.alter_column('user', 'enable',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment=None,
               existing_comment='1：启用，0：禁用')
    op.drop_index('name_unique', table_name='user')
    op.create_index(op.f('ix_user_avatar'), 'user', ['avatar'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_enable'), 'user', ['enable'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=False)
    op.alter_column('user_roles', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='对应user表中的id',
               existing_nullable=False)
    op.alter_column('user_roles', 'role_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='对应role表中的id',
               existing_nullable=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_foreign_key(None, 'user_roles', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.alter_column('user_roles', 'role_id',
               existing_type=mysql.INTEGER(),
               comment='对应role表中的id',
               existing_nullable=False)
    op.alter_column('user_roles', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='对应user表中的id',
               existing_nullable=False)
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_enable'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_avatar'), table_name='user')
    op.create_index('name_unique', 'user', ['name'], unique=False)
    op.alter_column('user', 'enable',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='1：启用，0：禁用')
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment='密码',
               existing_nullable=True)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment='用户名',
               existing_nullable=True)
    op.drop_index(op.f('ix_system_type'), table_name='system')
    op.drop_index(op.f('ix_system_system'), table_name='system')
    op.drop_index(op.f('ix_system_storage'), table_name='system')
    op.drop_index(op.f('ix_system_project'), table_name='system')
    op.drop_index(op.f('ix_system_memory'), table_name='system')
    op.drop_index(op.f('ix_system_ip'), table_name='system')
    op.drop_index(op.f('ix_system_id'), table_name='system')
    op.drop_index(op.f('ix_system_host'), table_name='system')
    op.drop_index(op.f('ix_system_env'), table_name='system')
    op.drop_index(op.f('ix_system_developer'), table_name='system')
    op.drop_index(op.f('ix_system_cpu'), table_name='system')
    op.drop_index(op.f('ix_system_admin'), table_name='system')
    op.alter_column('system', 'developer',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment='三线开发人员',
               existing_nullable=True)
    op.alter_column('system', 'project',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment='项目名称',
               existing_nullable=True)
    op.alter_column('system', 'type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment='物理机、虚拟机',
               existing_nullable=True)
    op.alter_column('system', 'env',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment='正式、测试环境',
               existing_nullable=True)
    op.alter_column('system', 'admin',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment='运维人员名字',
               existing_nullable=True)
    op.alter_column('system', 'cpu',
               existing_type=mysql.TINYINT(),
               comment='CPU数量',
               existing_nullable=True)
    op.alter_column('system', 'memory',
               existing_type=mysql.BIGINT(),
               comment='内存空间，单位G',
               existing_nullable=True)
    op.alter_column('system', 'storage',
               existing_type=mysql.BIGINT(),
               nullable=False,
               comment='硬盘空间，单位G')
    op.alter_column('system', 'system',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment='操作系统',
               existing_nullable=True)
    op.alter_column('system', 'ip',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               comment='IP地址',
               existing_nullable=True)
    op.alter_column('system', 'host',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=125),
               comment='主机名',
               existing_nullable=True)
    op.alter_column('system', 'info',
               existing_type=mysql.JSON(),
               comment='其他信息',
               existing_nullable=True)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_enable'), table_name='roles')
    op.drop_index(op.f('ix_roles_description'), table_name='roles')
    op.create_index('role_unique', 'roles', ['name'], unique=False)
    op.alter_column('roles', 'enable',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='1启用，0禁用',
               existing_server_default=sa.text("'1'"))
    op.alter_column('roles', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               nullable=True)
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               nullable=True,
               comment='角色名')
    op.drop_constraint(None, 'role_menu', type_='foreignkey')
    op.drop_constraint(None, 'role_menu', type_='foreignkey')
    op.drop_index(op.f('ix_role_menu_role_id'), table_name='role_menu')
    op.drop_index(op.f('ix_role_menu_menu_id'), table_name='role_menu')
    op.create_index('role_menu_unique', 'role_menu', ['role_id', 'menu_id'], unique=False)
    op.drop_constraint(None, 'role_category', type_='foreignkey')
    op.drop_constraint(None, 'role_category', type_='foreignkey')
    op.drop_index(op.f('ix_role_category_role_id'), table_name='role_category')
    op.drop_index(op.f('ix_role_category_category_id'), table_name='role_category')
    op.drop_index(op.f('ix_menu_url'), table_name='menu')
    op.drop_index(op.f('ix_menu_type'), table_name='menu')
    op.drop_index(op.f('ix_menu_path'), table_name='menu')
    op.drop_index(op.f('ix_menu_parent_id'), table_name='menu')
    op.drop_index(op.f('ix_menu_name'), table_name='menu')
    op.drop_index(op.f('ix_menu_id'), table_name='menu')
    op.drop_index(op.f('ix_menu_enable'), table_name='menu')
    op.drop_index(op.f('ix_menu_component'), table_name='menu')
    op.alter_column('menu', 'url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment='后端权限判断用的',
               existing_nullable=True)
    op.alter_column('menu', 'enable',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='菜单状态，1可用，0不可用',
               existing_server_default=sa.text("'1'"))
    op.alter_column('menu', 'type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               nullable=False,
               comment='page or button')
    op.alter_column('menu', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               comment='菜单名',
               existing_nullable=True)
    op.drop_index(op.f('ix_category_field_type'), table_name='category_field')
    op.drop_index(op.f('ix_category_field_show'), table_name='category_field')
    op.drop_index(op.f('ix_category_field_need'), table_name='category_field')
    op.drop_index(op.f('ix_category_field_name'), table_name='category_field')
    op.drop_index(op.f('ix_category_field_multi'), table_name='category_field')
    op.drop_index(op.f('ix_category_field_id'), table_name='category_field')
    op.drop_index(op.f('ix_category_field_desc'), table_name='category_field')
    op.drop_index(op.f('ix_category_field_category_id'), table_name='category_field')
    op.alter_column('category_field', 'category_id',
               existing_type=mysql.INTEGER(),
               comment='category表的外键',
               existing_nullable=True)
    op.alter_column('category_field', 'show',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否在资产页面显示字段，0：否，1：显示',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('category_field', 'multi',
               existing_type=mysql.TINYINT(display_width=1),
               comment='多值，0否，1是',
               existing_nullable=True)
    op.alter_column('category_field', 'need',
               existing_type=mysql.TINYINT(display_width=1),
               comment='必须，0否，1是',
               existing_nullable=True)
    op.alter_column('category_field', 'type',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               comment='字段类型：字符串text，整数number，日期时间date或datetime',
               existing_nullable=True)
    op.alter_column('category_field', 'desc',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               comment='字段描述',
               existing_nullable=True)
    op.alter_column('category_field', 'name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50),
               comment='字段',
               existing_nullable=True)
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_index(op.f('ix_category_desc'), table_name='category')
    op.drop_index(op.f('ix_category_alias'), table_name='category')
    op.alter_column('category', 'desc',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               comment='描述',
               existing_nullable=True)
    op.alter_column('category', 'alias',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               comment='资产类别别名（中文）',
               existing_nullable=True)
    op.alter_column('category', 'name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               comment='资产类别名（英文）',
               existing_nullable=True)
    op.create_foreign_key('assets_ibfk_1', 'assets', 'category', ['category'], ['name'])
    op.drop_index(op.f('ix_assets_user'), table_name='assets')
    op.drop_index(op.f('ix_assets_manager'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_deleted'), table_name='assets')
    op.drop_index(op.f('ix_assets_category'), table_name='assets')
    op.drop_index(op.f('ix_assets_area'), table_name='assets')
    op.alter_column('assets', 'deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='1：是，删除，0：否，未删除',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###
