"""更新菜单排序字段

Revision ID: b703662d9cf9
Revises: a5e2cea226d4
Create Date: 2022-10-31 10:22:22.613017

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b703662d9cf9'
down_revision = 'a5e2cea226d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu', 'sort',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_comment='菜单排序',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu', 'sort',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_comment='菜单排序',
               existing_nullable=True)
    # ### end Alembic commands ###
