"""init

Revision ID: cc553c35453a
Revises: 
Create Date: 2022-06-08 14:26:51.364287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc553c35453a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_role_category_category_id', table_name='role_category')
    op.drop_index('ix_role_category_role_id', table_name='role_category')
    op.drop_table('role_category')
    op.drop_table('casbin_rule')
    op.alter_column('assets', 'id',
               existing_type=mysql.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.drop_index('ix_assets_area', table_name='assets')
    op.drop_index('ix_assets_category', table_name='assets')
    op.drop_index('ix_assets_deleted', table_name='assets')
    op.drop_index('ix_assets_id', table_name='assets')
    op.drop_index('ix_assets_manager', table_name='assets')
    op.drop_index('ix_assets_user', table_name='assets')
    op.alter_column('category', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index('ix_category_alias', table_name='category')
    op.drop_index('ix_category_desc', table_name='category')
    op.drop_index('ix_category_id', table_name='category')
    op.drop_index('ix_category_name', table_name='category')
    op.alter_column('category_field', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index('ix_category_field_category_id', table_name='category_field')
    op.drop_index('ix_category_field_desc', table_name='category_field')
    op.drop_index('ix_category_field_id', table_name='category_field')
    op.drop_index('ix_category_field_multi', table_name='category_field')
    op.drop_index('ix_category_field_name', table_name='category_field')
    op.drop_index('ix_category_field_need', table_name='category_field')
    op.drop_index('ix_category_field_show', table_name='category_field')
    op.drop_index('ix_category_field_type', table_name='category_field')
    op.alter_column('menu', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index('ix_menu_component', table_name='menu')
    op.drop_index('ix_menu_enable', table_name='menu')
    op.drop_index('ix_menu_id', table_name='menu')
    op.drop_index('ix_menu_name', table_name='menu')
    op.drop_index('ix_menu_parent_id', table_name='menu')
    op.drop_index('ix_menu_path', table_name='menu')
    op.drop_index('ix_menu_type', table_name='menu')
    op.drop_index('ix_role_menu_menu_id', table_name='role_menu')
    op.drop_index('ix_role_menu_role_id', table_name='role_menu')
    op.alter_column('roles', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index('ix_roles_description', table_name='roles')
    op.drop_index('ix_roles_enable', table_name='roles')
    op.drop_index('ix_roles_id', table_name='roles')
    op.drop_index('ix_roles_name', table_name='roles')
    op.alter_column('sys_api', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('system', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index('ix_system_admin', table_name='system')
    op.drop_index('ix_system_cpu', table_name='system')
    op.drop_index('ix_system_developer', table_name='system')
    op.drop_index('ix_system_env', table_name='system')
    op.drop_index('ix_system_host', table_name='system')
    op.drop_index('ix_system_id', table_name='system')
    op.drop_index('ix_system_ip', table_name='system')
    op.drop_index('ix_system_memory', table_name='system')
    op.drop_index('ix_system_project', table_name='system')
    op.drop_index('ix_system_storage', table_name='system')
    op.drop_index('ix_system_system', table_name='system')
    op.drop_index('ix_system_type', table_name='system')
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50),
               nullable=False)
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_name', table_name='user')
    op.drop_index('name', table_name='user')
    op.drop_index('ix_user_roles_role_id', table_name='user_roles')
    op.drop_index('ix_user_roles_user_id', table_name='user_roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_roles_user_id', 'user_roles', ['user_id'], unique=False)
    op.create_index('ix_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    op.create_index('name', 'user', ['name', 'email'], unique=False)
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50),
               nullable=True)
    op.create_index('ix_system_type', 'system', ['type'], unique=False)
    op.create_index('ix_system_system', 'system', ['system'], unique=False)
    op.create_index('ix_system_storage', 'system', ['storage'], unique=False)
    op.create_index('ix_system_project', 'system', ['project'], unique=False)
    op.create_index('ix_system_memory', 'system', ['memory'], unique=False)
    op.create_index('ix_system_ip', 'system', ['ip'], unique=False)
    op.create_index('ix_system_id', 'system', ['id'], unique=False)
    op.create_index('ix_system_host', 'system', ['host'], unique=False)
    op.create_index('ix_system_env', 'system', ['env'], unique=False)
    op.create_index('ix_system_developer', 'system', ['developer'], unique=False)
    op.create_index('ix_system_cpu', 'system', ['cpu'], unique=False)
    op.create_index('ix_system_admin', 'system', ['admin'], unique=False)
    op.alter_column('system', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('sys_api', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index('ix_roles_name', 'roles', ['name'], unique=False)
    op.create_index('ix_roles_id', 'roles', ['id'], unique=False)
    op.create_index('ix_roles_enable', 'roles', ['enable'], unique=False)
    op.create_index('ix_roles_description', 'roles', ['description'], unique=False)
    op.alter_column('roles', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index('ix_role_menu_role_id', 'role_menu', ['role_id'], unique=False)
    op.create_index('ix_role_menu_menu_id', 'role_menu', ['menu_id'], unique=False)
    op.create_index('ix_menu_type', 'menu', ['type'], unique=False)
    op.create_index('ix_menu_path', 'menu', ['path'], unique=False)
    op.create_index('ix_menu_parent_id', 'menu', ['parent_id'], unique=False)
    op.create_index('ix_menu_name', 'menu', ['name'], unique=False)
    op.create_index('ix_menu_id', 'menu', ['id'], unique=False)
    op.create_index('ix_menu_enable', 'menu', ['enable'], unique=False)
    op.create_index('ix_menu_component', 'menu', ['component'], unique=False)
    op.alter_column('menu', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index('ix_category_field_type', 'category_field', ['type'], unique=False)
    op.create_index('ix_category_field_show', 'category_field', ['show'], unique=False)
    op.create_index('ix_category_field_need', 'category_field', ['need'], unique=False)
    op.create_index('ix_category_field_name', 'category_field', ['name'], unique=False)
    op.create_index('ix_category_field_multi', 'category_field', ['multi'], unique=False)
    op.create_index('ix_category_field_id', 'category_field', ['id'], unique=False)
    op.create_index('ix_category_field_desc', 'category_field', ['desc'], unique=False)
    op.create_index('ix_category_field_category_id', 'category_field', ['category_id'], unique=False)
    op.alter_column('category_field', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index('ix_category_name', 'category', ['name'], unique=False)
    op.create_index('ix_category_id', 'category', ['id'], unique=False)
    op.create_index('ix_category_desc', 'category', ['desc'], unique=False)
    op.create_index('ix_category_alias', 'category', ['alias'], unique=False)
    op.alter_column('category', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index('ix_assets_user', 'assets', ['user'], unique=False)
    op.create_index('ix_assets_manager', 'assets', ['manager'], unique=False)
    op.create_index('ix_assets_id', 'assets', ['id'], unique=False)
    op.create_index('ix_assets_deleted', 'assets', ['deleted'], unique=False)
    op.create_index('ix_assets_category', 'assets', ['category'], unique=False)
    op.create_index('ix_assets_area', 'assets', ['area'], unique=False)
    op.alter_column('assets', 'id',
               existing_type=mysql.BIGINT(),
               nullable=False,
               autoincrement=True)
    op.create_table('casbin_rule',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ptype', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('v0', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('v1', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('v2', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('v3', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('v4', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('v5', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('role_category',
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='role_category_ibfk_2'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='role_category_ibfk_1'),
    sa.PrimaryKeyConstraint('role_id', 'category_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_role_category_role_id', 'role_category', ['role_id'], unique=False)
    op.create_index('ix_role_category_category_id', 'role_category', ['category_id'], unique=False)
    # ### end Alembic commands ###
